-- CreateEnum
CREATE TYPE "StoreModule" AS ENUM ('COMPRAS', 'NOTAS_FISCAIS', 'SERVICOS', 'TRIBUTOS', 'PERDAS', 'CONTAS_A_PAGAR', 'TAREFAS', 'RELATORIOS', 'FUNCIONARIOS', 'FREELANCERS');

-- AlterTable
ALTER TABLE "Store" ADD COLUMN     "enabledModules" "StoreModule"[] DEFAULT ARRAY['COMPRAS', 'NOTAS_FISCAIS', 'SERVICOS', 'TRIBUTOS', 'PERDAS', 'CONTAS_A_PAGAR', 'TAREFAS', 'RELATORIOS', 'FUNCIONARIOS', 'FREELANCERS']::"StoreModule"[];
